
spring:
#  数据库链接
  datasource:
    url: jdbc:mysql://localhost:3306/campus_part_time_job?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: "root"
    password: "020407"
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
#  基准端口
  port: 8888
  servlet:
    context-path: /api/v1
    # 配置文件上传大小和总上传文件大小
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB



mybatis:
  configuration:
    map-underscore-to-camel-case: true


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true