@startuml
'https://plantuml.com/sequence-diagram

autonumber
'用户->注册页面:输入注册的信息
'注册页面->用户数据库:链接数据库
'用户数据库-->注册页面:注册失败，用户名重复
'用户数据库-->注册页面:注册失败，校验不通过
'用户数据库->用户数据库:写入用户数据库
'用户数据库->注册页面:提示注册成功
'用户-> 登录界面:输入用户名、密码
'登录界面-->用户:校验信息
'登录界面->用户数据库:根据账号密码查询用户信息
'用户数据库-->登录界面:返回查询结果&token
'登录界面->会员界面:跳转到各自权限的界面




'管理员->学生管理页:输入需要查询的数据
'学生管理页->后台服务器:将查询的信息传给后端
'后台服务器-->学生管理页:查询成功返回指定学生数据
'学生管理页-->管理员:将数据渲染给管理员
'后台服务器-->学生管理页:查询失败
'学生管理页-->管理员:返回错误信息
'
'管理员->学生管理页:编辑学生信息
'学生管理页->后台服务器:发送给后端
'后台服务器-->学生管理页:删除成功，返回最新数据
'学生管理页-->管理员:重新渲染最新数据
'后台服务器-->学生管理页:删除失败
'学生管理页-->管理员:返回404
'
'管理员->学生管理页:删除学生信息
'学生管理页->后台服务器:发送给后端
'后台服务器-->学生管理页:校验成功，返回最新数据
'学生管理页-->管理员:重新渲染最新数据
'后台服务器-->学生管理页:校验失败
'学生管理页-->管理员:返回404





'管理员->学生简历管理页面:查看学生简历
'学生简历管理页面->后台服务器:发送查询条件给后端
'后台服务器-->学生简历管理页面:返回指定的学生简历数据
'学生简历管理页面-->管理员:渲染指定的学生信息
'管理员->学生简历管理页面:删除学生简历
'学生简历管理页面->后台服务器:发送给后端
'后台服务器-->学生简历管理页面:删除成功
'学生简历管理页面-->管理员:重新渲染学生信息





'管理员->商家管理页:输入需要查询的数据
'商家管理页->后台服务器:将查询的信息传给后端
'后台服务器-->商家管理页:查询成功返回指定商家数据
'商家管理页-->管理员:将数据渲染给管理员
'后台服务器-->商家管理页:查询失败
'商家管理页-->管理员:返回错误信息
'
'管理员->商家管理页:编辑商家信息
'商家管理页->后台服务器:发送给后端
'后台服务器-->商家管理页:删除成功，返回最新数据
'商家管理页-->管理员:重新渲染最新数据
'后台服务器-->商家管理页:删除失败
'商家管理页-->管理员:返回404
'
'管理员->商家管理页:删除商家信息
'商家管理页->后台服务器:发送给后端
'后台服务器-->商家管理页:校验成功，返回最新数据
'商家管理页-->管理员:重新渲染最新数据
'后台服务器-->商家管理页:校验失败
'商家管理页-->管理员:返回404





'管理员->商店管理页:输入需要查询的数据
'商店管理页->后台服务器:将查询的信息传给后端
'后台服务器-->商店管理页:查询成功返回指定商店数据
'后台服务器-->招聘管理页:查询成功返回指定商店下的招聘数据
'后台服务器-->简历管理页:查询成功返回指定商店下的招聘下简历数据
'商店管理页-->管理员:将数据渲染给管理员
'后台服务器-->商店管理页:查询失败
'商店管理页-->管理员:返回错误信息
'
'管理员->商店管理页:编辑商店信息
'商店管理页->后台服务器:发送给后端
'后台服务器-->商店管理页:编辑成功，返回最新数据
'商店管理页-->管理员:重新渲染最新数据
'后台服务器-->商店管理页:编辑失败
'商店管理页-->管理员:返回错误信息
'
'管理员->招聘管理页:编辑招聘信息
'招聘管理页->后台服务器:发送给后端
'后台服务器-->招聘管理页:编辑成功，返回最新数据
'招聘管理页-->管理员:重新渲染最新数据
'后台服务器-->招聘管理页:编辑失败
'招聘管理页-->管理员:返回错误信息
'
'管理员->简历管理页:查看简历信息
'简历管理页->后台服务器:发送给后端
'后台服务器-->简历管理页:简历返回成功
'简历管理页-->管理员:渲染简历
'后台服务器-->简历管理页:返回失败
'简历管理页-->管理员:返回错误信息
'
'管理员->商店管理页:删除商店信息
'商店管理页->招聘管理页:删除招聘信息
'招聘管理页->简历管理页:删除简历信息
'商店管理页->后台服务器:发送给后端
'后台服务器-->商店管理页:删除成功，返回最新数据
'商店管理页-->管理员:重新渲染最新数据
'后台服务器-->商店管理页:删除失败
'商店管理页-->管理员:返回错误信息
'
'管理员->招聘管理页:删除招聘信息
'招聘管理页->简历管理页:删除简历信息
'商店管理页->后台服务器:发送给后端
'后台服务器-->商店管理页:删除成功，返回最新数据
'商店管理页-->管理员:重新渲染最新数据
'后台服务器-->商店管理页:删除失败
'商店管理页-->管理员:返回错误信息
'
'管理员->简历管理页:删除简历信息
'商店管理页->后台服务器:发送给后端
'后台服务器-->商店管理页:删除成功，返回最新数据
'商店管理页-->管理员:重新渲染最新数据
'后台服务器-->商店管理页:删除失败
'商店管理页-->管理员:返回错误信息





'管理员->评价管理页:查看所有学生评价数据
'评价管理页->后台服务器:请求获取所有学生评价数据
'后台服务器-->评价管理页:返回所有学生评价数据
'评价管理页-->管理员:渲染出所有数据
'后台服务器-->评价管理页:返回失败
'评价管理页-->管理员:返回错误信息





'商家->商店管理页:输入需要查询的数据
'商店管理页->后台服务器:将查询的信息传给后端
'后台服务器-->商店管理页:查询成功返回指定商店数据
'后台服务器-->招聘管理页:查询成功返回指定商店下的招聘数据
'商店管理页-->商家:将数据渲染给商家
'后台服务器-->商店管理页:查询失败
'商店管理页-->商家:返回错误信息
'
'商家->商店管理页:新增商店信息
'商店管理页->后台服务器:发送给后端且校验
'后台服务器-->商店管理页:校验失败
'商店管理页-->商家:返回错误信息
'后台服务器-->商店管理页:新增成功
'商店管理页-->商家:返回最新数据渲染
'
'商家->招聘管理页:新增招聘信息
'招聘管理页->后台服务器:发送给后端且校验
'后台服务器-->招聘管理页:校验失败
'招聘管理页-->商家:返回错误信息
'后台服务器-->招聘管理页:新增成功
'招聘管理页-->商家:返回最新数据渲染
'
'商家->商店管理页:编辑商店信息
'商店管理页->后台服务器:发送给后端
'后台服务器-->商店管理页:编辑成功，返回最新数据
'商店管理页-->商家:重新渲染最新数据
'后台服务器-->商店管理页:编辑失败
'商店管理页-->商家:返回错误信息
'
'商家->招聘管理页:编辑招聘信息
'招聘管理页->后台服务器:发送给后端
'后台服务器-->招聘管理页:编辑成功，返回最新数据
'招聘管理页-->商家:重新渲染最新数据
'后台服务器-->招聘管理页:编辑失败
'招聘管理页-->商家:返回错误信息
'
'商家->简历管理页:查看简历信息
'简历管理页->后台服务器:发送给后端
'后台服务器-->简历管理页:简历返回成功
'简历管理页-->商家:渲染简历
'后台服务器-->简历管理页:返回失败
'简历管理页-->商家:返回错误信息
'
'商家->商店管理页:删除商店信息
'商店管理页->招聘管理页:删除招聘信息
'招聘管理页->简历管理页:删除简历信息
'商店管理页->后台服务器:发送给后端
'后台服务器-->商店管理页:删除成功，返回最新数据
'商店管理页-->商家:重新渲染最新数据
'后台服务器-->商店管理页:删除失败
'商店管理页-->商家:返回错误信息
'
'商家->招聘管理页:删除招聘信息
'招聘管理页->简历管理页:删除简历信息
'商店管理页->后台服务器:发送给后端
'后台服务器-->商店管理页:删除成功，返回最新数据
'商店管理页-->商家:重新渲染最新数据
'后台服务器-->商店管理页:删除失败
'商店管理页-->商家:返回错误信息





'商家->学生简历管理页:查看简历信息
'学生简历管理页->后台服务器:请求发送给后端
'后台服务器-->学生简历管理页:所有简历返回成功
'简历管理页-->商家:渲染所有简历
'后台服务器-->简历管理页:返回失败
'简历管理页-->商家:返回错误信息
'
'商家->学生简历管理页:查看某简历信息
'学生简历管理页->后台服务器:请求发送给后端
'后台服务器-->学生简历管理页:某简历返回成功
'简历管理页-->商家:渲染所有简历
'后台服务器-->简历管理页:返回失败
'简历管理页-->商家:返回错误信息
'
'商家->学生简历管理页:通过某简历
'学生简历管理页->后台服务器:请求发送给后端
'后台服务器-->学生简历管理页:返回最新简历数据
'简历管理页-->商家:渲染新的简历数据
'后台服务器-->简历管理页:操作失败
'简历管理页-->商家:返回错误信息
'
'商家->学生简历管理页:淘汰某简历
'学生简历管理页->后台服务器:请求发送给后端
'后台服务器-->学生简历管理页:返回最新简历数据
'简历管理页-->商家:渲染新的简历数据
'后台服务器-->简历管理页:操作失败
'简历管理页-->商家:返回错误信息




'商家->个人中心页:查看个人信息
'个人中心页->后台服务器:请求发送给后端
'后台服务器-->个人中心页:返回个人信息成功
'个人中心页-->商家:渲染所有个人信息数据
'后台服务器-->个人中心页:返回失败
'个人中心页-->商家:返回错误信息
'
'商家->个人中心页:修改个人信息
'个人中心页->后台服务器:请求发送给后端且校验
'后台服务器-->个人中心页:返回个人最新信息成功
'个人中心页-->商家:渲染所有个人最新信息数据
'后台服务器-->个人中心页:返回失败
'个人中心页-->商家:返回错误信息
'
'商家->个人中心页:修改密码
'个人中心页->后台服务器:请求发送给后端且校验
'后台服务器-->个人中心页:返回成功信息
'后台服务器-->个人中心页:返回失败
'个人中心页-->商家:返回错误信息








'学生->兼职中心:查看兼职信息
'兼职中心->后台服务器:请求发送给后端
'后台服务器-->兼职中心:返回个人信息成功
'兼职中心-->学生:渲染所有兼职信息数据
'后台服务器-->兼职中心:返回失败
'兼职中心-->学生:返回错误信息
'
'学生->兼职中心:查看兼职详细信息
'兼职中心->后台服务器:请求发送给后端
'后台服务器-->兼职中心:返回兼职详细信息成功
'兼职中心-->学生:渲染兼职详细信息数据
'后台服务器-->兼职中心:返回失败
'兼职中心-->学生:返回错误信息
'
'学生->兼职中心:查询职位
'兼职中心->后台服务器:请求发送给后端
'后台服务器-->兼职中心:返回查询的职位成功
'兼职中心-->学生:渲染查询到的职位数据
'后台服务器-->兼职中心:返回失败
'兼职中心-->学生:返回错误信息
'
'学生->兼职中心:查询职位重置
'兼职中心->后台服务器:请求发送给后端
'后台服务器-->兼职中心:返回原本招聘信息成功
'兼职中心-->学生:渲染招聘信息
'后台服务器-->兼职中心:返回失败
'兼职中心-->学生:返回错误信息

'学生->兼职中心:上传简历并投递
'兼职中心->后台服务器:请求和简历数据发送给后端
'后台服务器-->兼职中心:返回投递信息成功
'兼职中心-->学生:渲染投递信息
'后台服务器-->兼职中心:返回失败
'兼职中心-->学生:返回错误信息

'学生->兼职中心:评价岗位
'兼职中心->后台服务器:请求发送给后端
'后台服务器-->兼职中心:返回评价信息成功
'兼职中心-->学生:渲染评价信息
'后台服务器-->兼职中心:返回失败
'兼职中心-->学生:返回错误信息

'学生->我的投递页面:查看投递信息
'我的投递页面->后台服务器:请求发送给后端
'后台服务器-->我的投递页面:返回投递信息成功，返回最新数据
'我的投递页面-->学生:渲染最新投递信息
'后台服务器-->我的投递页面:返回失败
'我的投递页面-->学生:返回错误信息
'
'学生->我的投递页面:撤销投递
'我的投递页面->后台服务器:请求发送给后端
'后台服务器-->我的投递页面:返回撤销信息成功，返回数据
'我的投递页面-->学生:渲染最新页面
'后台服务器-->我的投递页面:返回失败
'我的投递页面-->学生:返回错误信息

'学生->个人中心:查看个人信息
'个人中心->后台服务器:请求发送给后端
'后台服务器-->个人中心:返回个人信息成功
'个人中心-->学生:渲染个人信息页面
'后台服务器-->个人中心:返回失败信息
'个人中心-->学生:返回错误信息
'
'学生->个人中心:修改个人信息
'个人中心->后台服务器:请求和数据发送给后端
'后台服务器-->个人中心:修改成功，返回最新数据
'个人中心-->学生:渲染修改后的个人信息页面
'后台服务器-->个人中心:返回失败信息
'个人中心-->学生:返回错误信息
'
学生->个人中心:修改密码
个人中心->后台服务器:请求和数据发送给后端
后台服务器-->个人中心:修噶成功，返回最新数据
个人中心-->学生:渲染个人信息页面
后台服务器-->个人中心:返回失败信息
个人中心-->学生:返回错误信息



































@enduml